language: node_js
node_js:
  - "15.0.0"
sudo: false

branches:
  only:
    - master

install:
  - yarn install
  - npm install -g codecov

script:
  - yarn bootstrap
  - yarn build:lib
  - yarn run test

after_script:
  - codecov
