language: node_js
node_js:
  - "13.13.0"
sudo: false

branches:
  only:
    - master

install:
  - yarn install
  - npm install -g codecov

script:
  - yarn bootstrap
  - yarn build
  - yarn run test

after_script:
  - codecov
